const openBtn = document.getElementById("openBtn");
const bgMusic = document.getElementById("bgMusic");
const musicToggle = document.getElementById("musicToggle");
const dontClickBtn = document.getElementById("dontClickBtn");
const easterText = document.getElementById("easterText");
const giftResult = document.getElementById("giftResult");
const selectedGift = document.getElementById("selectedGift");
const selectedGiftImage = document.getElementById("selectedGiftImage");
const selectedGiftCategory = document.getElementById("selectedGiftCategory");
const confirmGift = document.getElementById("confirmGift");
const giftConfirmNote = document.getElementById("giftConfirmNote");
const finalSurprise = document.getElementById("finalSurprise");
const finalText = document.getElementById("finalText");
const confettiLayer = document.getElementById("confettiLayer");

let easterClicks = 0;
let currentGift = null;


/* =========================================================
   INTRO POPUP
========================================================= */
const introOverlay = document.getElementById("introOverlay");
const introOpenBtn = document.getElementById("introOpenBtn");
const siteContent = document.getElementById("siteContent");
const introLines = [...document.querySelectorAll(".intro-line")];

document.body.classList.add("intro-open");

const introDelays = [350, 1250, 2350, 3000, 4050];
introLines.forEach((line, i) => {
  setTimeout(() => line.classList.add("show"), introDelays[i] || 0);
});

introOpenBtn.addEventListener("click", async () => {
  try {
    bgMusic.currentTime = 0;
    await bgMusic.play();
    musicToggle.classList.add("playing");
    musicToggle.textContent = "❚❚";
  } catch (e) {
    console.log("Music could not start:", e);
  }

  siteContent.classList.remove("site-content-hidden");
  siteContent.classList.add("site-content-visible");

  introOverlay.classList.add("is-closing");
  document.body.classList.remove("intro-open");

  setTimeout(() => {
    introOverlay.remove();
  }, 800);

  burstConfetti(36);
});

openBtn.addEventListener("click", async () => {
  document.querySelectorAll(".reveal")[0]?.scrollIntoView({ behavior: "smooth" });
  try {
    await bgMusic.play();
    musicToggle.classList.add("playing");
    musicToggle.textContent = "❚❚";
  } catch (e) {}
  burstConfetti(30);
});

musicToggle.addEventListener("click", async () => {
  if (bgMusic.paused) {
    try {
      await bgMusic.play();
      musicToggle.classList.add("playing");
      musicToggle.textContent = "❚❚";
    } catch (e) {
      alert("Hãy thêm file music/our-song.mp3 để bật nhạc nhé.");
    }
  } else {
    bgMusic.pause();
    musicToggle.classList.remove("playing");
    musicToggle.textContent = "♫";
  }
});

dontClickBtn.addEventListener("click", () => {
  easterClicks += 1;
  const messages = [
    "Anh biết ngay là em sẽ bấm mà. 😑",
    "Seriously?",
    "Em vẫn bấm tiếp à? 😂",
    "Fine… I love you. ❤️"
  ];
  easterText.textContent = messages[Math.min(easterClicks - 1, messages.length - 1)];
  if (easterClicks >= 4) burstConfetti(42);
});

/* =========================================================
   DYNAMIC CONTENT
   Generated by UPDATE_CONTENT.bat -> data/content.js
========================================================= */
const CONTENT = window.BIRTHDAY_CONTENT || { memories: [], giftCategories: [] };

/* MEMORIES — horizontal swipe */
const memoryCarousel = document.getElementById("memoryCarousel");
const currentMemory = document.getElementById("currentMemory");
const totalMemory = document.getElementById("totalMemory");
const memoryDots = document.getElementById("memoryDots");
const swipeHint = document.getElementById("swipeHint");

function renderMemories() {
  memoryCarousel.innerHTML = "";
  memoryDots.innerHTML = "";

  const memories = CONTENT.memories || [];
  totalMemory.textContent = memories.length;
  currentMemory.textContent = memories.length ? 1 : 0;

  if (!memories.length) {
    memoryCarousel.innerHTML = `
      <div class="empty-content">
        Chưa có ảnh trong thư mục <b>memories</b>.<br>
        Thêm ảnh rồi chạy <b>UPDATE_CONTENT.bat</b>.
      </div>`;
    swipeHint.textContent = "";
    return;
  }

  memories.forEach((item, i) => {
    const card = document.createElement("article");
    card.className = "memory-slide" + (i === 0 ? " active" : "");
    card.dataset.index = i;

    const img = document.createElement("img");
    img.src = item.image;
    img.alt = item.title || `Kỷ niệm ${i + 1}`;

    const overlay = document.createElement("div");
    overlay.className = "memory-overlay";

    const chapter = document.createElement("span");
    chapter.textContent = item.chapter || `Chapter ${String(i + 1).padStart(2, "0")}`;

    const title = document.createElement("h3");
    title.textContent = item.title || `Memory ${i + 1}`;

    const meta = document.createElement("div");
    meta.className = "memory-meta";
    const metaParts = [];
    if (item.date) metaParts.push(item.date);
    if (item.location) metaParts.push(item.location);
    meta.textContent = metaParts.join(" · ");

    const desc = document.createElement("p");
    desc.textContent = item.description || "";

    overlay.append(chapter, title);
    if (metaParts.length) overlay.appendChild(meta);
    overlay.appendChild(desc);
    card.append(img, overlay);
    memoryCarousel.appendChild(card);

    const dot = document.createElement("button");
    dot.type = "button";
    dot.className = "memory-dot" + (i === 0 ? " active" : "");
    dot.setAttribute("aria-label", `Xem kỷ niệm ${i + 1}`);
    dot.addEventListener("click", () => {
      card.scrollIntoView({ behavior: "smooth", block: "nearest", inline: "center" });
    });
    memoryDots.appendChild(dot);
  });
}

renderMemories();

function getMemorySlides() {
  return [...document.querySelectorAll(".memory-slide")];
}
function getMemoryDots() {
  return [...document.querySelectorAll(".memory-dot")];
}

function updateMemoryActive() {
  const memorySlides = getMemorySlides();
  const dots = getMemoryDots();
  if (!memorySlides.length) return;

  const carouselRect = memoryCarousel.getBoundingClientRect();
  const center = carouselRect.left + carouselRect.width / 2;
  const maxDistance = Math.max(carouselRect.width * 0.72, 1);

  let bestIndex = 0;
  let bestDistance = Infinity;

  memorySlides.forEach((slide, i) => {
    const r = slide.getBoundingClientRect();
    const slideCenter = r.left + r.width / 2;
    const signedDistance = slideCenter - center;
    const distance = Math.abs(signedDistance);

    if (distance < bestDistance) {
      bestDistance = distance;
      bestIndex = i;
    }

    // 0 = centered, 1 = sufficiently far away
    const t = Math.min(distance / maxDistance, 1);

    // Continuous "page browsing" feel
    const scale = 1 - t * 0.10;
    const opacity = 1 - t * 0.52;
    const rotate = Math.max(-4.5, Math.min(4.5, signedDistance / carouselRect.width * 8));
    const translateY = t * 14;

    slide.style.setProperty("--page-scale", scale.toFixed(3));
    slide.style.setProperty("--page-opacity", opacity.toFixed(3));
    slide.style.setProperty("--page-rotate", `${rotate.toFixed(2)}deg`);
    slide.style.setProperty("--page-y", `${translateY.toFixed(1)}px`);
  });

  memorySlides.forEach((slide, i) => slide.classList.toggle("active", i === bestIndex));
  dots.forEach((dot, i) => dot.classList.toggle("active", i === bestIndex));
  currentMemory.textContent = bestIndex + 1;

  if (bestIndex > 0) swipeHint.style.opacity = "0.35";
  swipeHint.textContent =
    bestIndex === memorySlides.length - 1
      ? "Đã xem hết album ❤️"
      : "← vuốt để lật trang →";
}

let memoryRaf = null;
memoryCarousel.addEventListener("scroll", () => {
  cancelAnimationFrame(memoryRaf);
  memoryRaf = requestAnimationFrame(updateMemoryActive);
}, { passive: true });

window.addEventListener("resize", updateMemoryActive);
updateMemoryActive();

/* GIFTS — generated from /gifts folders */
const categoryTabs = document.getElementById("categoryTabs");
const productGrid = document.getElementById("productGrid");

function renderGiftTabs() {
  categoryTabs.innerHTML = "";
  const cats = CONTENT.giftCategories || [];

  if (!cats.length) {
    categoryTabs.innerHTML = `<span class="empty-inline">Chưa có category quà</span>`;
    productGrid.innerHTML = `
      <div class="empty-content">
        Chưa có quà trong thư mục <b>gifts</b>.<br>
        Tạo folder category, thêm ảnh + file .txt, rồi chạy <b>UPDATE_CONTENT.bat</b>.
      </div>`;
    return;
  }

  cats.forEach((cat, i) => {
    const btn = document.createElement("button");
    btn.className = "category-tab" + (i === 0 ? " active" : "");
    btn.dataset.category = cat.key;
    btn.textContent = `${cat.emoji || "🎁"} ${cat.label}`;
    btn.addEventListener("click", () => {
      [...categoryTabs.querySelectorAll(".category-tab")].forEach(t => t.classList.remove("active"));
      btn.classList.add("active");
      renderCategory(cat.key);
    });
    categoryTabs.appendChild(btn);
  });

  renderCategory(cats[0].key);
}

function renderCategory(categoryKey) {
  const category = (CONTENT.giftCategories || []).find(c => c.key === categoryKey);
  if (!category) return;

  productGrid.innerHTML = "";
  productGrid.scrollLeft = 0;
  giftResult.classList.add("hidden");
  currentGift = null;

  category.items.forEach((item) => {
    const btn = document.createElement("button");
    btn.className = "product-card";

    const img = document.createElement("img");
    img.src = item.image;
    img.alt = item.name;

    const info = document.createElement("div");
    info.className = "product-info";

    const strong = document.createElement("strong");
    strong.textContent = item.name;

    const small = document.createElement("small");
    small.textContent = item.note || "";

    info.append(strong, small);
    btn.append(img, info);

    btn.addEventListener("click", () => {
      document.querySelectorAll(".product-card").forEach(c => c.classList.remove("selected"));
      btn.classList.add("selected");

      currentGift = {
        ...item,
        category: category.label
      };

      selectedGift.textContent = item.name;
      selectedGiftImage.src = item.image;
      selectedGiftImage.alt = item.name;
      selectedGiftCategory.textContent = category.label;
      giftResult.classList.remove("hidden");
      giftConfirmNote.textContent = "";
      giftResult.scrollIntoView({ behavior: "smooth", block: "center" });
    });

    productGrid.appendChild(btn);
  });
}

renderGiftTabs();

confirmGift.addEventListener("click", () => {
  if (!currentGift) return;
  localStorage.setItem("birthdayGiftChoice", JSON.stringify(currentGift));
  giftConfirmNote.textContent = `Đã chốt: ${currentGift.name} (${currentGift.category}). Chụp màn hình đoạn này gửi anh nhé 😌`;
  burstConfetti(55);
});

finalSurprise.addEventListener("click", () => {
  finalText.textContent = "Plot twist: món quà tốt nhất vẫn chưa xuất hiện trên website này. ❤️";
  burstConfetti(80);
});

function burstConfetti(count = 40) {
  const icons = ["❤️", "✨", "🎉", "💗", "🌸"];
  for (let i = 0; i < count; i++) {
    const el = document.createElement("span");
    el.className = "confetti";
    el.textContent = icons[Math.floor(Math.random() * icons.length)];
    el.style.left = `${Math.random() * 100}%`;
    el.style.animationDuration = `${2.8 + Math.random() * 3.2}s`;
    el.style.animationDelay = `${Math.random() * .4}s`;
    el.style.fontSize = `${12 + Math.random() * 15}px`;
    confettiLayer.appendChild(el);
    setTimeout(() => el.remove(), 7000);
  }
}

const observer = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (entry.isIntersecting) entry.target.classList.add("visible");
  });
}, { threshold: .12 });

document.querySelectorAll(".reveal").forEach(el => observer.observe(el));
